from enum import Enum

class INSTITUTION_MESSAGING_TYPES(Enum):
  DEFAULT = 0
  SPLIT = 1
  GRADUAL = 2

messaging_file_names = {
  INSTITUTION_MESSAGING_TYPES.DEFAULT: 'default',
  INSTITUTION_MESSAGING_TYPES.SPLIT: '50-50',
  INSTITUTION_MESSAGING_TYPES.GRADUAL: 'gradual',
}

class INSTITUTION_ECOSYSTEM_TYPES(Enum):
  ONE_MIN = 0
  ONE_MAX = 1
  ONE_MID = 2
  TWO_POLARIZED = 3
  TWO_MID = 4
  THREE_POLARIZED = 5
  THREE_MID = 6

eco_file_names = {
  INSTITUTION_ECOSYSTEM_TYPES.ONE_MIN: 'one-min',
  INSTITUTION_ECOSYSTEM_TYPES.ONE_MAX: 'one-max',
  INSTITUTION_ECOSYSTEM_TYPES.ONE_MID: 'one-mid',
  INSTITUTION_ECOSYSTEM_TYPES.TWO_POLARIZED: 'two-polarized',
  INSTITUTION_ECOSYSTEM_TYPES.TWO_MID: 'two-mid',
  INSTITUTION_ECOSYSTEM_TYPES.THREE_POLARIZED: 'three-polarized',
  INSTITUTION_ECOSYSTEM_TYPES.THREE_MID: 'three-mid'
}